### PR TITLE
FindSecurityBugs plugin + FindBugs Security profile

### PR DESCRIPTION
**Pull request by h3xstream**
Hi,
These two commits include the plugin Find Security Bugs.
A new repository was added with the necessary tests.

https://jira.codehaus.org/browse/SONARFBUGS-18

### CODE REVIEW

**Comment by h3xstream** [comment]
Hi Nicolas!
Do you have an idea when you'll have time to integrate the change?

**Comment by benzonico** [comment]
Hi philippe, 
1st thanks for your contribution.

we want to do a small sprint on findbugs within a couple of weeks, I do hope to integrate your PR at this point. Given the quality of your code I think I'll accept it as is.
Thanks again.

**Comment by h3xstream** [comment]
Thanks that's perfect!

**Comment by m-g-sonar** [comment]
Hello,
Your pull request have been manually merged with the master!
Thank you for your contribution to the project!

**Pull request closed without merging**
