### PR TITLE
Update Find Security Bugs to version 1.4.2

### PR DESCRIPTION
**Pull request by h3xstream**
For more details https://github.com/h3xstream/find-sec-bugs/releases/tag/version-1.4.1

The next Sonar integration will be closer to the release plugin. The automation process is improving on my side.

@m-g-sonar Please edit the descriptions and tags in the [original project](https://github.com/h3xstream/find-sec-bugs) for future changes. The files are auto-generated. Many erroneous tagging were reverted. 1da2e7bca821901d3f0f37aa9d7b30bf5b5f333a
Editing auto-generated files makes it harder for everybody.

### CODE REVIEW

**Comment by formanek** [comment]
Please when do you expect the new version of FindSecurityBugs (and there is already a newer one) will be available in SonarQube? We would like to use the new features in analysis soon. Thank You.

**Comment by m-g-sonar** [comment]
Hello @h3xstream and @formanek, we will review this pull request and the update of FindSecurityBugs during next sprint on the findbug plugin. Feel free to update this pull request to include last version of FindSecurityBugs.

**Comment by h3xstream** [comment]
@m-g-sonar OK perfect! I will push the newer version ASAP.

**Comment by h3xstream** [comment]
## Quick note on the Sonar FindBugs plugin size

The enforcer rule on the max jar size triggered as follow:
```
[INFO] --- maven-enforcer-plugin:1.3.1:enforce (enforce-plugin-size) @ sonar-findbugs-plugin ---
[WARNING] Rule 0: org.apache.maven.plugins.enforcer.RequireFilesSize failed with message:
C:\Code\workspace-java\sonar-findbugs\target\sonar-findbugs-plugin-3.3-SNAPSHOT.jar size (7008716) too large. Max. is 7000000C:\Code\workspace-java\sonar-findbugs\target\sonar-findbugs-plugin-3.3-SNAPSHOT.jar
```

For this reason the max size was [increased slightly to 7.5MB (+500KB)](https://github.com/SonarSource/sonar-findbugs/commit/5799859a7786163f04c32284ba63755c91dc7334#diff-600376dffeb79835ede4a0b285078036L282). The rule will still identify unwanted dependencies added by mistake (if it was the objective).

**Comment by m-g-sonar** [comment]
Great! Thanks @h3xstream for your contribution! No problem extending the controlled size! I just started a sprint on findbugs, so I handle your PR as soon as possible!

**Comment by m-g-sonar** [comment]
@h3xstream Oh I just saw now your message about editing tags of rules! Sorry for that, I really didn't thought about it while doing the update. Be sure that I'll be careful on that subject next time!

I'll merge your PR this morning!

**Comment by m-g-sonar** [comment]
Merged!
Thanks again for your contribution!

**Pull request closed without merging**
